Repository N1ck49871/projeto_js_bc_porto, pull requests merged in 2023-07, with the labels that each got.

#8 html-Estrutura Form
  Css/styles.css
  Js/script.js
  index.html
Labels: enhancement

#10 HTML - Estrutura Form(Perguntas)
  quiz.html
Labels: enhancement

#11 Captura Form(Nome)
  Js/script.js
  Js/tema1.js
  index.html
Labels: enhancement

#14 Identação dos Códigos
  Js/script.js
  index.html
  quiz.html
  quizes/Perguntas-Respostas_Tema1.txt
  quizes/Perguntas-Respostas_Tema2.txt
  quizes/Perguntas-Respostas_Tema3.txt
Labels: enhancement

#13 updated readme
  README.md
Labels: documentation

#15 leaderboard
  leaderboard.html
Labels: enhancement

#19 Imagens do Tema 3
  img/at.png
  img/br.png
  img/bt.png
  img/d.png
  img/jg.png
  img/nv.png
  img/ps.png
  img/rt.png
  img/wm.png
  img/xb.png
Labels: enhancement

#18 stopwatch created (may need update to stop timer)
  Js/listRandomizer.js
  Js/timer.js
Labels: enhancement

#23 HTML - Botão Música/Reset
  img/pause-btn.png
  img/play-btn.png
  index.html
Labels: enhancement

#25 Css
  Css/dark.css
  Css/styles.css
  index.html
Labels: enhancement

#28 Adição do BootsTrap às página HTML
  index.html
  leaderboard.html
  quiz.html
Labels: enhancement

#29 Captura e entrega de dados Quiz
  Js/capturaFormPerguntas.js
  Js/quiz1.js
  Js/script.js
  quiz.html
Labels: enhancement

#30 Correçao do botão da Musica
  index.html
Labels: enhancement

#31 Botao para troca de temas
  img/dark-theme.png
  img/light-theme.png
  index.html
Labels: enhancement

#32 created audio controllers (music.js)
  Js/listRandomizer.js
  Js/music.js
Labels: enhancement

#37 Css
  Css/styles.css
  index.html
  leaderboard.html
  quiz.html
Labels: enhancement

#41 modulação dos arquivos CSS, container do display e tirei o autoplay d…
  Css/light.css
  Css/styles.css
  index.html
  quiz.html
Labels: bug, enhancement

#42 Perguntas e Respostas
  Js/capturaFormPerguntas.js
  Js/index.js
  Js/quiz.js
  Js/quiz1.js
  Js/quiz2.js
  Js/quiz3.js
  img/bt.png
  img/st.png
  quiz.html
  quizes/Perguntas-Respostas_Tema2.txt
  teste.html
Labels: enhancement

#48 Html css
  Css/styles.css
  Js/leaderboard.js
  leaderboard.html
Labels: enhancement

#53 Icones Bootstrap
  img/dark-theme.png
  img/light-theme.png
  img/pause-btn.png
  img/play-btn.png
  index.html
  teste.html
Labels: enhancement

#54 script de botoes index
  index.html
Labels: bug, enhancement

#56 corrected btns
  Js/buttonsAndTimer.js
Labels: bug

#57 Ponto no início das pastas para captura feita pelo github
  index.html
Labels: bug

#60 CSS - Estilizacao Quiz
  Css/dark.css
  Css/light.css
  Css/styles.css
  quiz.html
Labels: enhancement

#62 Respostas
  Js/quiz.js
  Js/quiz1.js
  Js/quiz2.js
  Js/quiz3.js
  Js/script.js
  index.html
  teste.html
Labels: enhancement

#63 Refactor code
  Css/new-dark.css
  Css/new-light.css
  Css/new-styles.css
  Js/newScript.js
  img/moon-flat.png
  img/pauseBtn.png
  img/playBtn.png
  img/sun-flat.png
  index.html
Labels: bug, enhancement

#64 novo tema
  Js/quiz3.js
  quizes/Perguntas-Respostas_Tema3.txt
Labels: enhancement

#65 Refactored Leaderboard | Created leaderboard page builder | linked all functions
  Css/new-dark.css
  Css/new-light.css
  Css/new-styles.css
  Js/newScript.js
Labels: bug, enhancement
